---
title: "combine_reef_check_with_cortad_variables_with_annual_rate_of_SST_change"
author: "SS"
date: "November 20, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r load libraries and read in csvs}
library(chron)
library(RColorBrewer)
library(lattice)
library(ncdf4)
library(stringr)

main_working_directory="C:/Users/Shannon/Desktop/Ecoregions"
#main_working_directory="C:/RobsR/Shannon/Bleaching data"

setwd(main_working_directory)
#read in the Reef Check csv
RC_with_cortad_variables <- read.csv(file="Reef_Check_with_cortad_variables.csv", header=TRUE, sep=",")

annual_rate_of_SST_change<- read.csv(file="SST_rate_of_change_NOAA_1_km_res.csv", header=TRUE, sep=",")

diversity_data<-read.csv(file="Coral_diversity_numbers.csv")

ECO<-readOGR(ecoregion_polygons_directory,"ecoregion_exportPolygon")
```

```{r read in ecoregion shape files and do the overlay to determine which ecoregion each study falls into}

coordinates(RC_with_cortad_variables)<- ~Longitude.Degrees+Latitude.Degrees
proj4string(RC_with_cortad_variables)<-"+proj=longlat +ellps=WGS84 +datum=WGS84"
bldata<-spTransform(RC_with_cortad_variables,proj4string(ECO))

#get the ecoregion number for each study. NA means the study falls outside all ecoregion areas
test<-over(bldata,ECO)
RC_with_cortad_variables$Region<-as.character(test$ERG)

for (i in 1:length(RC_with_cortad_variables$Region))
{
  if(length(RC_with_cortad_variables$Region)>0){
    RC_with_cortad_variables$Region[i]= as.numeric(strsplit(RC_with_cortad_variables$Region[i], split="G")[[1]][2])
  }
}
RC_with_cortad_variables$Region<-as.numeric(RC_with_cortad_variables$Region)

RC_with_cortad_variables$Diversity<-NA
for (i in 1:length(RC_with_cortad_variables$Region))
{
  if (!is.na(RC_with_cortad_variables$Region[i]))
  {
    RC_with_cortad_variables$Diversity[i]<-diversity_data$SpeciesAccepted[(diversity_data$Ecoregion==RC_with_cortad_variables$Region[i])]
  }
}
```



```{r combine csvs and write new csv Reef_Check_with_cortad_variables_with_annual_rate_of_SST_change.csv}
RC_with_cortad_variables_with_annual_rate_of_SST_change<-cbind(RC_with_cortad_variables, "rate_of_SST_change"=annual_rate_of_SST_change[,2])

write.csv(RC_with_cortad_variables_with_annual_rate_of_SST_change, "Reef_Check_with_cortad_variables_with_annual_rate_of_SST_change.csv")
```